# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: cryptobox
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin